[phases.setup]
aptPkgs = ["python3", "make", "gcc", "g++"]

[phases.install]
cmds = ["npm ci --ignore-scripts"]

[phases.build]
cmds = [
  "npm rebuild better-sqlite3 --build-from-source",
  "npm run postinstall",
  "npm run build"
]

[start]
cmd = "node .output/server/index.mjs"
