[phases.setup]
nixPkgs = ["nodejs", "python3", "gnumake", "gcc"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "npm rebuild better-sqlite3 --build-from-source"
]

[start]
cmd = "node .output/server/index.mjs"
